version: '3.7'
services: 
  selenium-hub:
    image: selenium/hub:3.141.59-yttrium
    container_name: selenium-hub
    ports:
      - "4444:4444"
  firefox:
    image: selenium/node-firefox:3.141.59-yttrium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
  mysql:
    image: mysql:5
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      - .data/mysql:/var/lib/mysql
      - ./mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    container_name: 'mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=!@#sspaas@U0
      - MYSQL_DATABASE=ku
    restart: always
    ports:
      - 127.0.0.1:3306:3306

